# Generated by Django 5.2.7 on 2025-10-21 16:55

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("openalex_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=512)),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        size=None,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("pdf_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "pdf_path",
                    models.FileField(blank=True, null=True, upload_to="pdfs/"),
                ),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["doi"], name="literature__doi_d7271a_idx"),
                    models.Index(
                        fields=["openalex_id"], name="literature__openale_e92783_idx"
                    ),
                ],
                "unique_together": {("doi", "openalex_id")},
            },
        ),
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("topic", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("searching_openalex", "Searching OpenAlex"),
                            ("downloading_pdfs", "Downloading PDFs"),
                            ("extracting_text", "Extracting Text"),
                            ("summarizing_papers", "Summarizing Papers"),
                            ("generating_review", "Generating Review"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=155, null=True),
                ),
                ("result", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True, related_name="review_tasks", to="literature.paper"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
