# Generated by Django 5.2.7 on 2025-10-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="papers_downloaded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewtask",
            name="papers_found",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewtask",
            name="papers_summarized",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewtask",
            name="progress_percent",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="reviewtask",
            name="total_papers_target",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
