# Generated by Django 5.2.7 on 2025-10-22 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "literature",
            "0002_reviewtask_papers_downloaded_reviewtask_papers_found_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewtask",
            options={},
        ),
        migrations.RemoveField(
            model_name="reviewtask",
            name="celery_task_id",
        ),
        migrations.AddField(
            model_name="reviewtask",
            name="papers_extracted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reviewtask",
            name="current_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("searching_openalex", "Searching OpenAlex"),
                    ("downloading_pdfs", "Downloading PDFs"),
                    ("extracting_text", "Extracting Text"),
                    ("summarizing_papers", "Summarizing Papers"),
                    ("generating_review", "Generating Final Review"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reviewtask",
            name="papers",
            field=models.ManyToManyField(
                related_name="review_tasks", to="literature.paper"
            ),
        ),
        migrations.AlterField(
            model_name="reviewtask",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="reviewtask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
