# Generated by Django 5.2.7 on 2025-10-09 13:12

import django.db.models.deletion
import litapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteratureReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                (
                    "content",
                    models.TextField(
                        help_text="AI-generated literature review content (3000+ words)"
                    ),
                ),
                (
                    "citations",
                    models.JSONField(
                        default=dict, help_text="Mapping of paper_id → citation string"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="literature_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiteratureReviewJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_text", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked completed review, if available",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job",
                        to="litapp.literaturereview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lit_review_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openalex_id", models.CharField(max_length=50, unique=True)),
                ("title", models.TextField()),
                (
                    "authors",
                    models.TextField(help_text="Comma-separated list of authors"),
                ),
                ("year", models.IntegerField()),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("pdf_url", models.URLField(blank=True, null=True)),
                (
                    "cached_file",
                    models.FileField(
                        blank=True,
                        help_text="Cached local copy of PDF",
                        null=True,
                        upload_to=litapp.models.pdf_cache_path,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Extracted full text from the PDF"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year"],
                "indexes": [
                    models.Index(
                        fields=["openalex_id"], name="litapp_pape_openale_8c392e_idx"
                    ),
                    models.Index(fields=["year"], name="litapp_pape_year_9de2fb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("prompt", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked Celery job for the search, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_records",
                        to="litapp.literaturereviewjob",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked final literature review, if available",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_records",
                        to="litapp.literaturereview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="literaturereview",
            index=models.Index(fields=["topic"], name="litapp_lite_topic_888d8f_idx"),
        ),
        migrations.AddIndex(
            model_name="literaturereview",
            index=models.Index(
                fields=["created_at"], name="litapp_lite_created_6b654f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="literaturereviewjob",
            index=models.Index(fields=["status"], name="litapp_lite_status_b63096_idx"),
        ),
        migrations.AddIndex(
            model_name="literaturereviewjob",
            index=models.Index(
                fields=["created_at"], name="litapp_lite_created_b53380_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["user", "timestamp"], name="litapp_sear_user_id_1dbe67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(fields=["topic"], name="litapp_sear_topic_5668a6_idx"),
        ),
    ]
